spring.application.name=apigateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gaeway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-server-id=true
server.port=7077

spring.cloud.gateway.routes[0].id=swiggy
spring.cloud.gateway.routes[0].uri=lb://SWIGGY
spring.cloud.gateway.routes[0].predicates[0]=Path=/swiggy/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1